# Generated by Django 4.1.3 on 2022-11-14 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patient', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('birth_date', models.DateField()),
                ('blood_group', models.CharField(max_length=20)),
                ('allergies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medicalcard.allergy')),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='patient.userprofile')),
            ],
        ),
    ]
